# Generated by Django 4.0.4 on 2022-05-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yezhu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='yezhu',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yezhu',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
